.github/workflows/tests.yml, CHANGES.md, README.md, docs/mongodb.md, examples/mongodb_cdc_cratedb.py, pyproject.toml, src/commons_codec/transform/mongodb.py, tests/transform/test_mongodb.py
Similar to the [transformer for DynamoDB CDC events](https://github.com/daq-tools/commons-codec/commit/114b3c937c), this patch adds a little converter which takes care of [MongoDB Change Stream](https://www.mongodb.com/docs/manual/changeStreams/) events. In this case, it translates ingress CDC events into SQL statements suitable for [CrateDB](https://github.com/crate/crate).
The [Relay MongoDB Change Stream into CrateDB](https://github.com/daq-tools/commons-codec/blob/mongodb/docs/mongodb.md) document describes how to get started using the [basic relay example program](https://github.com/daq-tools/commons-codec/blob/mongodb/examples/mongodb_cdc_cratedb.py).
=> Transform: MongoDB CDC event to CrateDB SQL

CHANGES.md, src/commons_codec/transform/dynamodb.py, tests/transform/test_dynamodb.py
CrateDB does not allow changing primary key columns, even when setting them to their current value.
This probably applies to other transformers as well (DMS and MongoDB).
=> DynamoDB: Skip primary key columns in `SET` clause for `UPDATE` statements

CHANGES.md, src/commons_codec/transform/aws_dms.py, tests/transform/test_aws_dms.py
CrateDB does not allow changing primary key columns, even when setting them to their current value.
=> DMS: Skip primary key columns in `SET` clauses for `UPDATE` statements

CHANGES.md, src/commons_codec/transform/dynamodb.py, tests/transform/test_dynamodb.py
In the long term, we might need to look up the original data type and decide more selectively how to pass different data types. For now, let's pass everything as a string and leave it to CrateDB to auto-cast values.
This fixes a reported issue:
```
sqlalchemy.exc.ProgrammingError: (crate.client.exceptions.ProgrammingError) ColumnUnknownException[Column tt unknown]
[SQL: UPDATE "poc" SET data['test'] = tt WHERE data['PK'] = 'pk' AND data['SK'] = 'sk';]
(Background on this error at: https://sqlalche.me/e/20/f405)
```
=> DynamoDB: Wrap all values in UPDATE statements in quotes

CHANGES.md, src/commons_codec/transform/dynamodb.py, src/commons_codec/util/data.py, tests/transform/test_dynamodb.py
When computing values for `UPDATE` statements, consider the data type of the value. It aims to improve GH-19 by @hammerhead.
=> DynamoDB: Apply rough type evaluation and dispatching

src/commons_codec/transform/dynamodb.py, tests/transform/test_dynamodb.py
Same like GH-27, but implemented by extending the AWS-vendorized code instead of changing it. Intends to fix GH-26.
=> DynamoDB: Fix `String Set` and `Number Set` representation to CrateDB.

CHANGES.md, src/commons_codec/transform/dynamodb.py, src/commons_codec/util/data.py, tests/transform/test_dynamodb.py
The translator produced invalid SQL when processing empty strings.
```sql
data['notes'] = ,
```
=> DynamoDB: Fix serializing empty strings

CHANGES.md, src/commons_codec/transform/dynamodb.py, tests/transform/test_dynamodb.py
=> DynamoDB: Fix object (Map) representation to CrateDB

CHANGES.md, src/commons_codec/transform/dynamodb.py, tests/transform/test_dynamodb.py
Another attempt to get relaying container type values right, this time for both OBJECTs and ARRAYs, at least a basic variant thereof, in order to unblock people needing it.
The problem with ARRAYs is that they can't be relayed using JSON syntax, supported by a corresponding CAST. Instead, we need to use the native notation of CrateDB, which works without much ado on primitive inner types.
When serializing ARRAYs including OBJECT inner types, we need to actively convert to CrateDB's native syntax, which is close to Python's `dict(foo='bar')` syntax notation.
- GH-33
=> DynamoDB: Fix serializing OBJECT and ARRAY representations to CrateDB

CHANGES.md, src/commons_codec/model.py, src/commons_codec/transform/aws_dms.py, src/commons_codec/transform/dynamodb.py, src/commons_codec/transform/mongodb.py, tests/transform/test_aws_dms.py, tests/transform/test_dynamodb_cdc.py, tests/transform/test_dynamodb_full.py, tests/transform/test_mongodb.py
At the core of this patch is the introduction of the `SQLOperation` class, which bundles together an SQL statement and its parameters, in order to convey those instances to callers, instead of rendering a full-fledged SQL statement in string format, which is problematic because of string escaping issues.
https://github.com/crate/commons-codec/blob/3f9dfe5a8e55e7024b18b852778d27d4408551e7/src/commons_codec/model.py#L87-L96
- `SQLOperation` bundles data about an SQL operation, including statement and parameters.
- `DynamoDBFullLoadTranslator` supports full-load data transfers.
This patch will need relevant adjustments in CrateDB Toolkit, effectively converging into releases of both packages in lock-step.
- https://github.com/crate/cratedb-toolkit/pull/243
/cc @surister, @hammerhead, …
=> DMS/DynamoDB/MongoDB: Use SQL with parameters instead of inlining values

CHANGES.md, pyproject.toml, src/commons_codec/model.py, src/commons_codec/transform/aws_dms.py, src/commons_codec/transform/dynamodb.py, tests/transform/test_aws_dms.py, tests/transform/test_dynamodb_cdc.py
Following up on https://github.com/crate/commons-codec/pull/35#pullrequestreview-2260314090, this patch also introduces parameterized WHERE clauses within the DMS and DynamoDB I/O adapter implementations.
That other PR validates the patch on behalf of CrateDB Toolkit.
- https://github.com/crate/cratedb-toolkit/pull/244
=> DMS/DynamoDB: Use parameterized SQL WHERE clauses instead of inlining

CHANGES.md, examples/mongodb_cdc_cratedb.py, pyproject.toml, src/commons_codec/model.py, src/commons_codec/transform/dynamodb.py, src/commons_codec/transform/mongodb.py, tests/test_model.py, tests/transform/test_aws_dms.py, tests/transform/test_dynamodb_cdc.py, tests/transform/test_dynamodb_full.py, tests/transform/test_mongodb.py
~~When needed, use `quote_relation_name` from `sqlalchemy-cratedb` package. Otherwise, don't quote at all, and push this responsibility to the caller. I think it is better doing it this way, than doing it wrong.~~
Instead of doing it insufficiently, let's pay the price on pulling in the `sqlalchemy-cratedb` package as a dependency, to be able to use the canonical implementation `quote_relation_name` without further ado.
- https://github.com/crate/sqlalchemy-cratedb/pull/155
=> Replace poor man's relation name quoting with implementation from `sqlalchemy-cratedb`

tests/transform/test_dynamodb_full.py
Apply a round of "naming things" and cleanups to DynamoDB tests.
=> DynamoDB: Compress transformation tests into single one. Naming things.

.github/workflows/tests.yml, README.md, doc/development.md, pyproject.toml, tests/transform/conftest.py, tests/transform/test_dynamodb_cdc.py, tests/transform/test_dynamodb_full.py, tests/transform/test_dynamodb_types_cratedb.py, tests/transform/test_dynamodb_types_vanilla.py, tests/transform/test_mongodb.py
This patch adds an integration test with CrateDB for the `DynamoDBFullLoadTranslator`.
=> DynamoDB: Add integration test for full-load operation

CHANGES.md, src/commons_codec/model.py, src/commons_codec/transform/dynamodb.py, tests/transform/test_dynamodb_full.py
In order to support batch operations, make the `to_sql()` method accept a list of records.
- https://github.com/crate/cratedb-toolkit/pull/252
/cc @wierdvanderhaar, @hlcianfagna
=> DynamoDB: Improve `to_sql()` to accept list of records

CHANGES.md, src/commons_codec/transform/mongodb.py, tests/transform/mongodb/data.py
One more decoding fix for MongoDB Extended JSON elements.
=> MongoDB: Fix edge case when decoding MongoDB Extended JSON elements

CHANGES.md, doc/zyp/backlog.md, doc/zyp/examples.md, doc/zyp/index.md, src/commons_codec/transform/mongodb.py, src/zyp/model/base.py, src/zyp/model/bucket.py, src/zyp/model/moksha.py, src/zyp/model/treatment.py, src/zyp/util/data.py, tests/zyp/moksha/test_jq.py, tests/zyp/moksha/test_model.py, tests/zyp/moksha/test_transon.py, tests/zyp/test_bucket.py, tests/zyp/test_moksha.py
It's all about Zyp.
- Add capability to skip rule evaluation when `disabled: true`
- Documentation
- How to delete attributes from lists using `jq`
- How to conditionally manipulate nested attributes
- Update index and backlog pages
- Tests: Improve test cases for `to_object`
=> [Zyp] This and that: Mostly documentation and software tests

CHANGES.md, doc/zyp/backlog.md, src/commons_codec/transform/mongodb.py, src/zyp/function.jq, src/zyp/model/moksha.py, tests/transform/mongodb/data.py, tests/transform/mongodb/test_mongodb_convert.py, tests/transform/mongodb/test_mongodb_full.py, tests/zyp/moksha/test_jq.py, tests/zyp/moksha/test_model.py
Assorted "this and that" refinements.
- [MongoDB: Also decode non-UUID binary values](https://github.com/crate/commons-codec/commit/4e59c98058cc8bea4b0bf777dc729181d93350ba)
- [MongoDB: Satisfy mypy on MongoDBCrateDBConverter.decode_canonical](https://github.com/crate/commons-codec/pull/57/commits/6f75a106fe985690973bc81b6714871d61ac44ca)
- [MongoDB: Improve MongoDBCrateDBConverter.decode_extended_json](https://github.com/crate/commons-codec/pull/57/commits/5370381bb527c301cb516fc4f5fab5dc8b92d90f)
- [Zyp/Moksha/jq: to_object function now respects a zap option](https://github.com/crate/commons-codec/commit/403416594c452070f18c8beb804c66eb310a8401)
- [Zyp/Moksha/jq: Improve error reporting at MokshaTransformation.apply](https://github.com/crate/commons-codec/pull/57/commits/f97c040067b40242 …
=> Zyp and MongoDB: A few adjustments and refinements

CHANGES.md, src/commons_codec/transform/dynamodb.py, tests/transform/test_dynamodb_cdc.py, tests/transform/test_model.py
> Hey guys, I noticed earlier that DynamoDB updates that removed fields from items were not synced properly to CrateDB, would you know why?
When breaking down CDC MODIFY statements into individual SET clauses, deleted attributes would not be propagated correctly.
Don't break down into SET clauses, but insert data from `NewImage` as-is.
@hammerhead, @surister: Please review retroactively. Thank you!
=> DynamoDB CDC: Fix `MODIFY` operation by propagating `NewImage` fully

CHANGES.md, src/zyp/model/moksha.py, tests/zyp/moksha/test_model.py
When transformation payload is a `map()`, and jqlang rule evaluation fails, improve error reporting.
=> Zyp/Moksha: Improve error reporting when rule evaluation fails

CHANGES.md, src/commons_codec/model.py, src/commons_codec/transform/dynamodb.py, src/commons_codec/transform/dynamodb_model.py, tests/transform/conftest.py, tests/transform/test_dynamodb_cdc.py, tests/transform/test_dynamodb_full.py, tests/transform/test_dynamodb_model.py, tests/transform/test_dynamodb_types_cratedb.py
By breaking the primary key information out of the main record's data bucket, the main record can be updated as-is on CDC MODIFY operations.
- https://github.com/crate/cratedb-toolkit/pull/281
=> DynamoDB: Change CrateDB data model to use (`pk`, `data`, `aux`) columns

CHANGES.md, src/commons_codec/transform/mongodb.py, src/zyp/model/moksha.py, tests/transform/mongodb/data.py, tests/zyp/moksha/test_model.py
- [MongoDB: Handle too large $date.$numberLong values gracefully](https://github.com/crate/commons-codec/commit/7242c9486bf5001b0be32ad22203d0d2354cf6df)
- [Zyp/Moksha: Improve error reporting when rule evaluation fails](https://github.com/crate/commons-codec/commit/6f08fbb3f247daf214d87682fd39b54bf1995b50)
=> Improvements for Zyp/Moksha error reporting and MongoDB `$date.$numberLong` values

CHANGES.md, src/commons_codec/transform/mongodb.py, tests/transform/conftest.py, tests/transform/mongodb/test_mongodb_convert.py
- [MongoDB: Fixed BSON decoding of {"$date": 1180690093000} timestamps](https://github.com/crate/commons-codec/commit/865b73357fabc0af590a1c9a7263b78b14f1431c)
- [DynamoDB: Use CrateDB 5.8.3 for testing. 5.8.4 caught a regression](https://github.com/crate/commons-codec/commit/d2214fb234b17b24daa0930d32e254f3248bf233)
=> DynamoDB and MongoDB: Fix CI and improve decoding

CHANGES.md, tests/transform/conftest.py
=> DynamoDB/Testing: Use CrateDB nightly again

CHANGES.md, src/commons_codec/transform/dynamodb.py, tests/transform/test_dynamodb_cdc.py
... to mitigate errors when events are relayed redundantly from retries after partially failed batches on the Lambda processor.
- https://github.com/crate/cratedb-toolkit/issues/301
/cc @kneth, @surister, @hlcianfagna
=> DynamoDB: Use `ON CONFLICT DO NOTHING` clause on `INSERT` CDC operations

CHANGES.md, src/commons_codec/transform/aws_dms.py, tests/transform/test_aws_dms.py
A few more fixes about processing CDC events from DMS/Kinesis regarding the "universal" column mapping paradigm.
- GH-110
=> DMS: Fix primary key / where clause rendering
